# Generated by Django 5.1.7 on 2025-03-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='available_quantity',
        ),
    ]
